TDIPSNetCore/Controllers/ECREAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
using TDIPS.Core.Interfaces;
using TDIPS.Core.Models;
using TDIPS.Infrastructure.Business_Logic;

namespace TDIPSNetCore.Web.Controllers
{
    [Authorize(Policy = "DenyNonTreasury")]
    public class ECREAController : Controller
    {
        IQueueRepository QueueRepository = new QueueRepository();
        IQueueingWindow IQueueingWindow = new QueueingWindowRepository();
        IVoucherRepository VoucherRepository = new VoucherRepository();
        IVendorRepository VendorRepository = new VendorRepository();
        IECREAManagerRepository ECREAManagerRepository = new ECREAManagerRepository();

        private readonly IWebHostEnvironment _webHostEnvironment;

        private readonly IHubContext<CompanyCallHub> _hub;

        public ECREAController(IWebHostEnvironment hostingEnvironment, IHubContext<CompanyCallHub> hub)
        {
            _webHostEnvironment = hostingEnvironment;
            _hub = hub;
        }

        private static Random random = new Random();

        static async Task SynthesizeAudioAsync(string text, string filepath)
        {
            var config = SpeechConfig.FromSubscription("92be2c4978d341e387049d55db64c40d", "southeastasia");
            using var audioConfig = AudioConfig.FromWavFileOutput(filepath);
            using var synthesizer = new SpeechSynthesizer(config, audioConfig);
            await synthesizer.SpeakTextAsync(text);
        }

        public void Speak(string textToSpeech, string filename)
        {
        //    // Command to execute PS  

        //    var cmd = $@"
        //        Add-Type -AssemblyName System.Speech
        //        $soundFilePath = ""C:\Users\dizon\Desktop\Projects\TDIPSNetCore\TDIPSNetCore\wwwroot\t2s\test.wav""
        //        [System.Speech.Synthesis.SpeechSynthesizer] $voice = $null
        //        Try {{
        //        $voice = New-Object -TypeName System.Speech.Synthesis.SpeechSynthesizer
        //        $voice.SetOutputToWaveFile($soundFilePath)
        //        $voice.SelectVoice(""Microsoft Zira Desktop"")
        //        $voice.Speak(""testing fdalksfafkjalkfjalkfjkads"")
        //        }}
        //                    Finally {{
        //                        if ($voice) {{
        //        $voice.Dispose()
        //                        }}
        //    }};";

        //    Execute(cmd);
        

        //void Execute(string command)
        //    {
        //        // create a temp file with .ps1 extension  
        //        var cFile = _webHostEnvironment.ContentRootPath + "/wwwroot/t2s/test.ps1";

        //        //Write the .ps1  
        //        using var tw = new System.IO.StreamWriter(cFile, false, Encoding.UTF8);
        //        tw.Write(command);

        //        // Setup the PS  
        //        var start =
        //            new System.Diagnostics.ProcessStartInfo()
        //            {
        //                FileName = "C:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe",  // CHUPA MICROSOFT 02-10-2019 23:45                    
        //                LoadUserProfile = false,
        //                UseShellExecute = false,
        //                CreateNoWindow = true,
        //                Arguments = $"-executionpolicy bypass -File {cFile}",
        //                WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden
        //            };

        //        //Init the Process  

        //        try
        //        {
        //            var p = System.Diagnostics.Process.Start(start);
        //            p.WaitForExit();
        //        }
        //        catch (Exception ex)
        //        {

        //            throw;
        //        }
        //    }
        }

        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        // GET: ECREA
        [AllowAnonymous]
        public ActionResult QueueingWindow()
        {
            return View();
        }
        [AllowAnonymous]
        public JsonResult GetQueueList(int rowNumber = -1, string status = "")
        {
            return Json(QueueRepository.GetQueueList(rowNumber, status));
        }

        //[CustomAuthorize("!AUDIT")]
        [Authorize(Policy = "DenyAudit")]
        public ActionResult Management()
        {
            ViewBag.IsKioskRatingActivated = ECREAManagerRepository.IsKioskRatingActivated();

            return View();
        }

        public ActionResult GetLastECREARatings()
        {
            return Json(ECREAManagerRepository.GetLastECREARatings());
        }

        private string ReplaceFirstOccurrence(string Source, string Find, string Replace)
        {
            int Place = Source.IndexOf(Find, StringComparison.CurrentCultureIgnoreCase);
            string result = Source;

            if (Place > -1)
            {
                result = Source.Remove(Place, Find.Length).Insert(Place, Replace);
            }

            return result;
        }

        public ActionResult IsKioskRatingActivated()
        {
            return Json(ECREAManagerRepository.IsKioskRatingActivated());
        }

        public async Task<ActionResult> TTS(string text, string companyName, string collectorName, int queueNumber, string queueType, int repeat = 0)
        {
            text = ReplaceFirstOccurrence(text, "INC.", "incorporated. ");

            for (int i = 0; i < repeat; i++)
            {
                text += text;
            }

            NumberCall n = new NumberCall
            {
                Type = "NUMBER CALL",
                CompanyName = companyName,
                QueueType = queueType,
                QueueNumber = queueNumber,
                Status = "READY",
                Text = text,
                CollectorName = collectorName
            };

            var callid = IQueueingWindow.AddNumberCall(n);
            string fileName = "TTS" + callid;

            //Speak(text, fileName + ".wav");

            BackgroundJob.Schedule(
            () => DeleteAudioWhenDone(callid),
            TimeSpan.FromMinutes(5));

            var filepath = _webHostEnvironment.WebRootPath + "\\Queueing Window\\TTS\\" + fileName + ".wav";

            await SynthesizeAudioAsync(text, filepath);

            await _hub.Clients.All.SendAsync("CompanyCall", "SYSTEM", callid.ToString() + "_" + queueType);

            return Json(fileName + ".wav");
        }

        [HttpPost]
        public string SaveVideo(IFormFile videofile)
        {
            var splitfilename = videofile.FileName.Split('\\');
            var filename = splitfilename[splitfilename.Length - 1];

            if (!(filename.EndsWith(".mp4") || filename.EndsWith(".avi") || filename.EndsWith(".mov") || filename.EndsWith(".flv") || filename.EndsWith(".wmv")))
            {
                return "invalid format";
            }

            if (videofile != null)
            {
                var filenames = videofile.FileName.ToString().Split('.');
                string fileextension = filenames[filenames.Length - 1];
                int videoid = IQueueingWindow.SaveVideo(filename, fileextension, User.Identity.Name);
                videofile.SaveAs(_webHostEnvironment.WebRootPath + "//Queueing Window//Videos//" + videoid.ToString() + "." + fileextension);
                
                return "SUCCESS";
            }
            return "FAILED";
        }

        [AllowAnonymous]
        public ActionResult GetVideoList()
        {
            return Json(IQueueingWindow.VideoList());
        }

        public ActionResult SetKioskRatingActivation(bool isActivate)
        {
            ECREAManagerRepository.SetKioskRatingActivation(isActivate);

            return Json("SUCCESS");
        }

        public string SaveMarqueeText(string text)
        {
            return IQueueingWindow.SaveMarqueeText(text, User.Identity.Name);
        }

        [AllowAnonymous]
        public string GetMarqueeText()
        {
            return IQueueingWindow.GetMarqueeText();
        }

        public string DeleteVideo(int videoId, string fileExtension)
        {
            string fullPath = _webHostEnvironment.WebRootPath + "/Queueing Window/Videos/" +  videoId + "." + fileExtension.ToString();

            if (System.IO.File.Exists(fullPath))
            {
                IQueueingWindow.DeleteVideo(videoId, User.Identity.Name);
                System.IO.File.Delete(fullPath);

                return "SUCCESS";
            }

            return "FAILED";
        }

        public JsonResult ReleaseVoucher(ReleasedVoucher[] r, int queueId, bool isInQueue = true, VoucherCollector c = null, string vendorCode = "")
        {
            if (isInQueue)
            {
                QueueRepository.DeleteFromQueue(queueId);
            }

            string jobId = BackgroundJob.Enqueue(() => VoucherRepository.UpdateCollectedVouchers(r, c));

            return Json(VoucherRepository.ReleaseVoucher(r, User.Identity.Name));
        }

        public ActionResult Release()
        {
            return View();
        }

        public ActionResult Dequeue(int queueId)
        {
            return Json(QueueRepository.Dequeue(queueId, User.Identity.Name));
        }

        public ActionResult Queue(int queueId)
        {
            return Json(QueueRepository.Queue(queueId, User.Identity.Name));
        }

TDIPSNetCore/Views/ECREA/CheckCompany.cshtml
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<div class="page-title pb-3">
    <div class="title_left" style="width:100% !important;">
        <h3>Vendors Module</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Vendor List</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="dtVendor" class="table jambo_table bulk_action dataTable no-footer" cancelmergeurl="@Url.Action("CancelMerge", "SEAN")"
                       mergeurl="@Url.Action("MergeVendor","SEAN")" url="@Url.Action("GetVendorList","SEAN")">
                    <thead>
                        <tr>
                            <th>Entity</th>
                            <th>Vendor Code</th>
                            <th>Company Name</th>
                            <th>Company Email</th>
                            <th>Contact No.</th>
                            <th>Company Address</th>
                            <th>Actions</th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--- Modals -->

<div class="modal fade" id="modalViewVouchers" url="@Url.Action("ReleaseVoucher","ECREA")" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
    <div style="width:1100px;" class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"> <strong></strong></h4>
            </div>
            <div class="modal-body">
                <div class="container_collector_details" style="border-bottom:#ccc solid 1px;padding-bottom:30px;">
                    <h4 style="margin-top:3px;margin-bottom:17px;font-weight:600;">Collector's Details</h4>
                    <div style="display:flex; justify-content:space-around">
                        <div style="flex:auto;padding-right:30px;">
                            <label for="txtCollectorName">Collector Name:</label>
                            <input class="form-control" type="text" id="txtCollectorName" />
                        </div>
                        <div style="flex:auto;padding-right:30px;">
                            <label for="txtCollectorType">Collector Type:</label>
                            <select class="form-control" id="txtCollectorType">
                                <option value="AUTHORIZED">Authorized Collector</option>
                                <option value="THIRD PARTY">Third Party Collector</option>
                            </select>
                        </div>
                        <div style="display:none;flex:auto;">
                            <label for="txtThirdPartyCompany">Third Party Company:</label>
                            <input class="form-control" type="text" id="txtThirdPartyCompany" />
                        </div>
                    </div>

                </div>


                <div class="col-12" style="margin-top:20px !important; margin-bottom:20px !important;">
                    <table id="dtVoucher" class="table jambo_table bulk_action" url="@Url.Action("GetForReleasingVoucherList","SEAN")">
                        <thead>
                            <tr>
                                <th>Voucher Number</th>
                                <th>Entity</th>
                                <th>Bank</th>
                                <th>Amount</th>
                                <th>Check Number</th>
                                <th>Check Date</th>
                                <th>Type</th>
                                <th>Receipt Number</th>
                                <th>Receipt Type</th>
                            </tr>
                        </thead>

                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnRelease" class="btn btn-primary">Release</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts_source {
    <script src="@Url.Content("~/js/datatable.js")"></script>

    
    <script src="@Url.Content("~/js/Page JS/checkcompany.js")"></script>
}

@section styles {
    <link href="~/css/datatable.css" rel="stylesheet" />
}

TDIPSNetCore/Views/ECREA/Management.cshtml
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<style>
    .page_title {
        padding-top: 55px !important;
        display: block;
        font-size: 26px;
        padding-bottom: 8px;
        padding-left: 2px;
    }

    video {
        background-color: #131315;
        border-radius: 2px;
    }

    .container_txt_btn {
            display: inherit;
            flex-direction: inherit;
            align-items: inherit;
            flex-grow: 1;
            justify-content: space-evenly;
    }

    .panel_title {
        font-weight: 500;
        font-size: 21px;
    }

    #txtAnnouncement {
        width: 95%;
        margin-top: 10px;
        margin-bottom: 12px;
        border: 2px solid #ccc;
        font-size: 17px;
        font-weight: 500;
        background-color: #F1F1F1;
    }

    input[type=file] {
        padding-top: 4px;
        padding-left: 3px;
        border: solid 1px #ccc;
        margin-left: 6px;
        padding-bottom: 2px;
    }

    .video_container {
        display: flex;
        justify-content:space-around;
        padding-top: 34px;
        flex-wrap: wrap;
        border: solid 1px #ccc;
        border-radius: 5px;
        margin-top: 20px;
    }

    .div_video {
        background-color: #F1F1F1;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding-top: 20px;
        padding-right: 15px;
        padding-left: 15px;
        border-radius: 2px;
        margin-bottom: 26px;
        border: solid 1px #ccc;
    }

    .video_title {
        font-size: 19px;
        font-weight: 500;
        text-align: center;
        margin-top: 15px;
        overflow-wrap: break-word;
    }

    .video_container .btn-danger {
        width: 110px;
        margin-top: 5px;
        margin-bottom: 20px;
    }

    .title_container {
        width: 380px;
        text-align: center;
    }

    @@media only screen and (max-width: 768px) {
        .panel_title {
            width:100% !important;
        }

        .md-flex {
            flex-wrap:wrap;
        }

            .md-flex input[type=file] {
                width:210px !important;
                margin-left:0px !important;
            }

        video {
            width:80%;
            height:auto;
        }

        .div_video {
            background-color:white;
            border: unset !important;
        }

        .video_container {
            border:unset !important;
        }

        .right_col {
           background-color:white !important;
        }
    }
</style>


<h1 class="page_title" style="font-weight:600;">Queueing Window Management</h1>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="panel_title">Announcement Text <small style="font-weight:600;">modify text in marquee that goes from right to left. (max: 500)</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div style="display:flex; justify-content:center">
                    <textarea saveUrl="@Url.Action("SaveMarqueeText", "ECREA")" url="@Url.Action("GetMarqueeText", "ECREA")"  maxlength="500" id="txtAnnouncement" class="form-control" rows="4"></textarea>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="panel_title">Kiosk Rating</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p>
                    <input @if(ViewBag.IsKioskRatingActivated == true) { <text>checked</text>} type="checkbox" id="cbxActivateRating" class="flat"> Activate rating window in ECREA Kiosk
                </p>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="panel_title">Advertisement Videos</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form enctype="multipart/form-data" class="form-horizontal" method="post" autocomplete="off" id="frmUploadVideo" url="@Url.Action("SaveVideo")" novalidate>
                    <fieldset>
                        <div class="md-flex" style="display:flex;">
                            <label style="font-weight:500;font-size:17px;padding-top:2px;">Upload Video File :</label>
                            <div style="display:flex">
                                @Html.TextBox("videofile", "", new { type = "file", accept = ".mp4, .avi, .mov, .flv, .wmv", style="width: 360px;" })
                                <input type="button" id="btnUploadVideo" value="Upload" />
                            </div>
                        </div>
                    </fieldset>
                </form>

                <div class="video_container" url="@Url.Action("GetVideoList","ECREA")" deleteUrl="@Url.Action("DeleteVideo", "ECREA")" source="@Url.Content("~/Queueing Window/Videos")/">
                </div>
                
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
</div>

@section scripts_source {
    <script src="@Url.Content("~/js/Page JS/management.js")"></script>
}

TDIPSNetCore/Views/ECREA/QueueingWindow.cshtml
<html>
<head>
    <title>Queing Window</title>
    <link rel="stylesheet" href=@Url.Content("~/css/QueueingWindow.css")>
</head>
<body url="@Url.Action("GetQueueList","ECREA")">
    <div class="top_bar">
        <label>SHAKEY'S ELECTRONIC CHECK RELEASING EXPRESS ASSIST</label>
    </div>
    <div class="main">
        <div class="left_area">
        </div>
        <div class="right_area">
            <div class="container_video" style="position:relative;height:50vh;">
                <div style="position:relative;">
                    <video id="video0" onended="PlayNext()" class='video_player' source="@Url.Content("~/Queueing Window/Videos")/" url="@Url.Action("GetVideoList","ECREA")" width="100%" height="100%" autoplay autobuffer controls></video>
                </div>
            </div>
            <div id="container_datetime">
                <div class="container_datetime date">
                    <label></label>
                </div>
                <div class="container_datetime time">
                    <label></label>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div url="@Url.Action("GetMarqueeText", "ECREA")" style="width:max-content;" id="txtAnnouncement">

        </div>
        @*<marquee id="txtAnnouncement" url="@Url.Action("GetMarqueeText", "ECREA")" scrollamount="10" width="100%" direction="left" height="100%">
        </marquee>*@
    </div>
    <div id="container_audio" style="display:none" deleteurl="@Url.Action("DeleteAudioWhenDone","ECREA")" getcallurl="@Url.Action("GetCall","ECREA")" source="@Url.Content("~/Queueing Window/TTS")/" url="@Url.Action("TTS", "ECREA")">

    </div>

    <audio id="beep_shakeys" volume="0.1" controls src="@Url.Content("~/Queueing Window/beep_shakeys.mp3")" style="display:none"></audio>
</body>
</html>

<script src="@Url.Content("~/js/home.bundle.js")"></script>
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="@Url.Content("~/js/marquee.js")"></script>
<script src="@Url.Content("~/js/date.format.js")"></script>
<script src="@Url.Content("~/js/jquery.textfill.min.js")"></script>
<script src="@Url.Content("~/js/browser.checker.js")"></script>
<script src="@Url.Content("~/js/Page JS/QueueWindow.js")"></script>

TDIPSNetCore/Views/ECREA/Release.cshtml
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<style>
    .page_title {
        padding-top: 55px !important;
        display: block;
        font-size: 26px;
        padding-bottom: 8px;
        padding-left: 2px;
    }

    .panel-title {
        font-weight: 500;
        font-size: 21px;
        overflow: unset !important;
    }

    .row_action {
        width: 80px;
    }

    .container_collector_details label {
        font-size: 16px;
    }

    .priority_row {
        background: rgba(254,211,48, 0.4);
    }

    .regular_row {
        background: rgba(32,191,107, 0.3);
    }

    @@media only screen and (max-width: 768px) {
        .md-flex {
            flex-wrap:wrap;
        }

            .md-flex > div:nth-child(2) > div:nth-child(1), .md-flex > div:nth-child(2) > div:nth-child(2) {
                margin-left: 0px !important;
            }

            .md-flex > div:nth-child(2) {
                margin-top:2px;
                justify-content:space-between;
            }
    }
</style>

<h1 class="page_title">Vouchers List Ready for Release</h1>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="border: 1px solid #ccc">
            <div class="x_title">
                <div class="md-flex" style="display:flex;">
                    <div>
                        <h2 class="panel-title" style="margin-top:4px !important;">In Queue List</h2>
                    </div>
                    <div style="display:flex;">
                        <div style="margin-left:20px;margin-top:1px;">
                            <button queueType="REGULAR" class="btn btn-sm btn-primary btnCall">Call Regular Number</button>
                        </div>
                        <div style="margin-left:12px;margin-top:1px;">
                            <button queueType="PRIORITY" class="btn btn-sm btn-success btnCall">Call Priority Number</button>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="dtQueue" class="table jambo_table bulk_action" dequeueurl="@Url.Action("Dequeue", "ECREA")" queueurl="@Url.Action("Queue", "ECREA")" url="@Url.Action("GetQueueList", "ECREA")">
                    <thead>
                        <tr>
                            <th>Queue Number</th>
                            <th>Queue Type</th>
                            <th>Company Name</th>
                            <th>Collector Name</th>
                            <th>Collector Type</th>
                            <th>Third Party Company</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
</div>

<div class="row" style="margin-top:18px;">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="border: 1px solid #ccc;background-color:#efeaea;">
            <div class="x_title">
                <div style="display:flex; border-bottom: 2px solid #ccc;">
                    <div>
                        <h2 class="panel-title" style="margin-top:4px !important;">Dequeued List</h2>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="dtDequeue" class="table jambo_table bulk_action" dequeueurl="@Url.Action("Dequeue", "ECREA")">
                    <thead style="background-color:#262626">
                        <tr>
                            <th>Queue Number</th>
                            <th>Queue Type</th>
                            <th>Company Name</th>
                            <th>Collector Name</th>
                            <th>Collector Type</th>
                            <th>Third Party Company</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
</div>

<div id="container_audio" style="display:none" source="@Url.Content("~/Queueing Window/TTS")/" url="@Url.Action("TTS", "ECREA")">
</div>

<div class="modal fade" id="modalViewVouchers" url="@Url.Action("ReleaseVoucher","ECREA")" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" style="width:1100px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"> <strong></strong></h4>
            </div>
            <div class="modal-body">
                <div class="container_collector_details" style="border-bottom:#ccc solid 1px;padding-bottom:30px;">
                    <h4 style="margin-top:3px;margin-bottom:17px;font-weight:600;">Collector's Details</h4>
                    <div style="display:flex; justify-content:space-around">
                        <div style="flex:auto;padding-right:30px;">
                            <label for="txtCollectorName">Collector Name:</label>
                            <input class="form-control" type="text" id="txtCollectorName" />
                        </div>
                        <div style="flex:auto;padding-right:30px;">
                            <label for="txtCollectorType">Collector Type:</label>
                            <select class="form-control" id="txtCollectorType">
                                <option value="AUTHORIZED">Authorized Collector</option>
                                <option value="THIRD PARTY">Third Party Collector</option>
                            </select>
                        </div>
                        <div style="display:none;flex:auto;">
                            <label for="txtThirdPartyCompany">Third Party Company:</label>
                            <input class="form-control" type="text" id="txtThirdPartyCompany" />
                        </div>
                    </div>
                    
                </div>


                <div class="col-12" style="margin-top:20px !important; margin-bottom:20px !important;">
                    <table id="dtVoucher" class="table jambo_table bulk_action" url="@Url.Action("GetForReleasingVoucherList","SEAN")">
                        <thead>
                            <tr>
                                <th>Entity</th>
                                <th>Bank</th>
                                <th>Voucher Number</th>
                                <th>Amount</th>
                                <th>Check Number</th>
                                <th>Check Date</th>
                                <th>Type</th>
                                <th>Receipt Number</th>
                                <th>Receipt Type</th>
                            </tr>
                        </thead>

                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnRelease" class="btn btn-primary">Release</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


@section styles {
    <link href="~/css/datatable.css" rel="stylesheet" />
}

@section scripts_source {
    <script src="@Url.Content("~/js/datatable.js")"></script>
    <script src="@Url.Content("~/js/Page JS/release.js")"></script>
}