TDIPSNetCore/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TDIPS.Core.Interfaces;
using TDIPS.Infrastructure.Business_Logic;

namespace TDIPSNetCore.Web.Controllers
{
    //[CustomAuthorize("!AP", "!AUDIT")]
    [Authorize(Policy = "DenyAudit")]
    public class SystemController : Controller
    {
        ISystemLogRepository SystemLogRepository = new SystemLogRepository();
        IMailRepository MailRepository = new MailRepository();
        IBackupRepository BackupRepository = new BackupRepository();
        // GET: System

        public ActionResult Logs()
        {
            return View();
        }

        public ActionResult GetSystemLogsList(Nullable<DateTime> dateFrom = null, Nullable<DateTime> dateTo = null, string type = "")
        {
            var resultData = SystemLogRepository.List(dateFrom, dateTo, type);
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(resultData, Formatting.Indented),
                ContentType = "application/json"
            };

            return result;
        }


        public ActionResult GetMailLogsList(DateTime dateFrom, DateTime dateTo)
        {
            var resultData = MailRepository.MailLogs(dateFrom, dateTo);
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(resultData, Formatting.Indented),
                ContentType = "application/json"
            };

            return result;
        }

        public ActionResult MailLogs()
        {
            return View();
        }

        public ActionResult TrackMailStatus()
        {
            return Json(MailRepository.TrackMailStatus());
        }

        public ActionResult Backup()
        {
            return View();
        }

        public ActionResult GetBackupFiles()
        {
            string[] files = Directory.GetFiles(@"c:\Backup\", "*.bak", SearchOption.AllDirectories);
            List<string> filelist = new List<string>();

            for (int i = 0; i < files.Length; i++)
            {
                filelist.Add(files[i]);
            }

            return Json(filelist.ToList());
        }

        public ActionResult DownloadBackup(string filename)
        {
            string file = @"c:\backup\" + filename;
            return File(file, "bak", Path.GetFileName(file));
        }
    }
}

TDIPSNetCore/Views/System/Backup.cshtml
@{
    ViewBag.Title = "Backup";
}

<div class="page-title pb-3">
    <div class="title_left">
        <h3>Backup & Restore</h3>
    </div>
</div>
<div class="clearfix"></div>

<div class="row" style="margin-top:11px;">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <form enctype="multipart/form-data" method="post" id="frmUpload">
                    <fieldset>
                        <div style="display:flex;justify-content:space-between;">
                            <div>
                                <h2>Backup Schedule Options</h2>
                            </div>
                            <div class="input-group" style="width:50px;">
                                <span class="input-group-btn">
                                    <button style="height:31px;" type="button" id="btnUpload" class="btn btn-sm btn-success">Restore from my Computer</button>
                                </span>
                                <input type="file" name="FileUpload" required accept=".bak" class="input-sm">
                            </div>
                        </div>
                        


                        @*<div style="display:flex;margin-top:12px;margin-bottom:15px;">
                <div style="flex:auto;">
                    <label style="font-size:17px;" for="cbxRecurrence">Recurrence</label>
                    <select name="cbxRecurrence" id="cbxRecurrence" class="form-control">
                        <option>Daily</option>
                        <option>Weekly</option>
                    </select>
                </div>
            </div>*@
                    </fieldset>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="x_content">
                <table id="dtBackup" class="table jambo_table bulk_action dataTable no-footer">
                    <thead>
                        <tr>
                            <th>Time of Backup</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalDialog" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" style="width:40% !important;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title text-warning"><b>Confirmation Dialog <i class="fa fa-warning"></i></b></h4>
            </div>
            <div class="modal-body">
                <h5><b class="dialog-message">Please type your password to confirm.</b></h5>
                <div style="margin-top:15px;">
                    <input placeholder="" autocomplete="false" type="password" id="txtPassword" class="form-control" />
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" id="btnAcceptRestore" class="btn btn-primary">Proceed and Restore</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<style>
    input[type=file] {
        border: #8a8484 1px solid;
        padding-bottom: 24px !important;
        border-radius: 0px;
        border-left: white 0px solid;
    }
</style>

@section scripts_source {
    <script src="@Url.Content("~/js/datatable.js")"></script>
    <script src="@Url.Content("~/js/Page JS/backup.js")"></script>
}

TDIPSNetCore/Views/System/Logs.cshtml
@{
    ViewBag.Title = "Logs";
}

<div class="page-title pb-3">
    <div class="title_left">
        <h3 style="margin-bottom:15px;">System Logs</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <div style="margin-top:10px;">
                    <div style="width:60% !important; float:left;">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button id="btnSearch" class="btn btn-sm btn-success"><i class="fa fa-search"></i> Search</button>
                            </span>
                            <input type="text" style="width: 200px" readonly="readonly" id="dtrSearch" class="form-control input-sm" value="@DateTime.Now.ToString("MM/dd/yyyy") - @DateTime.Now.ToString("MM/dd/yyyy")">
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="dtLogs" class="table table-striped jambo_table bulk_action" url="@Url.Action("GetSystemLogsList","System")">
                    <thead>
                        <tr>
                            <th>Date/Time</th>
                            <th>User</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section styles {
    <link href="~/css/datatable.css" rel="stylesheet" />
    <link href="~/css/daterangepicker.css" rel="stylesheet" />
}


@section scripts_source {
    <script src="@Url.Content("~/js/datatable.js")"></script>
    <script src="@Url.Content("~/js/Gentelella Template/validator.js")"></script>
    <script src="@Url.Content("~/js/moment.min.js")"></script>
    <script src="@Url.Content("~/js/Gentelella Template/validator.js")"></script>
    <script src="@Url.Content("~/js/daterangepicker.js")"></script>
    <script src="@Url.Content("~/js/Page JS/logs.js")"></script>
}

TDIPSNetCore/Views/System/MailLogs.cshtml
@{
    ViewBag.Title = "MailLogs";
}

<div class="page-title pb-3">
    <div class="title_left" style="width:100% !important;">
        <div style="display:flex;justify-content:space-between;">
            <h3 style="margin-bottom:19px;">Mail Logs</h3>
            <div class="input-group" style="margin-top:10px;width:50px;">
                <span class="input-group-btn">
                    <button id="btnSearch" class="btn btn-sm btn-success"><i class="fa fa-search"></i> Search</button>
                </span>
                <input type="text" style="width: 200px" readonly="readonly" id="dtrSearch" class="form-control input-sm" value="@DateTime.Now.ToString("MM/dd/yyyy") - @DateTime.Now.AddDays(1).ToString("MM/dd/yyyy")">
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h4 style="font-size:22px;" id="statusMsg"></h4>
                <div id="containerprogress"></div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="dtMailLogs" urlstatus="@Url.Action("TrackMailStatus","System")" class="table table-striped jambo_table bulk_action" url="@Url.Action("GetMailLogsList","System")">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<style>
    .progressbar-text {
        color: rgb(153, 153, 153) !important;
        position: relative !important;
        text-align: right !important;
        font-size: 16px !important;
        font-weight: 700 !important;
        color: #252323 !important;
    }
</style>


@section styles {
    <link href="~/css/datatable.css" rel="stylesheet" />
    <link href="~/css/daterangepicker.css" rel="stylesheet" />
}

@section scripts_source {
    <script src="@Url.Content("~/js/datatable.js")"></script>
    <script src="@Url.Content("~/js/moment.min.js")"></script>
    <script src="@Url.Content("~/js/daterangepicker.js")"></script>
    <script src="@Url.Content("~/js/progressbar.min.js")"></script>
    <script src="@Url.Content("~/js/daterangepicker.js")"></script>
    <script src="@Url.Content("~/js/Page JS/maillogs.js")"></script>
}