TDIPSNetCore/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using TDIPS.Core.Interfaces;
using TDIPS.Core.Models;
using TDIPS.Infrastructure.Business_Logic;

namespace TDIPSNetCore.Web.Controllers
{
    [Authorize(Policy = "DenyNonTreasury")]
    public class ReportController : Controller
    {
        ISystemLogRepository SystemLogRepository = new SystemLogRepository();
        IVoucherRepository VoucherRepository = new VoucherRepository();
        IMailRepository MailRepository = new MailRepository();
        IEODRepository EODRepository = new EODRepository();
        IEmployeeRepository EmployeeRepository = new EmployeeRepository();
        GlobalClass GlobalClass = new GlobalClass();

        private readonly IWebHostEnvironment _webHostEnvironment;

        public ReportController(IWebHostEnvironment hostingEnvironment)
        {
            _webHostEnvironment = hostingEnvironment;
        }

        // GET: Report
        public ActionResult Aging()
        {
            return View();
        }

        public ActionResult CollectedCheckReport()
        {
            return View();
        }

        public ActionResult DownloadExcel(string fileName)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(_webHostEnvironment.WebRootPath +
                "/SpreadSheets/Reports/" + fileName + ".xlsx");
            string fileName2 = fileName + ".xlsx";

            BackgroundJob.Schedule(
            () => DeleteExcelFile(_webHostEnvironment.WebRootPath + "~/SpreadSheets/Reports/" + fileName + ".xlsx"),
            TimeSpan.FromMinutes(5));

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName2);
        }

        public void DeleteExcelFile(string fullpath)
        {
            if (System.IO.File.Exists(fullpath))
            {
                System.IO.File.Delete(fullpath);
            }
        }

        public string GetRowsFromRange(string range)
        {
            var result = range.Split(':');
            return result[0].Substring(1, result[0].Length - 1) + ":" + result[1].Substring(1, result[1].Length - 1);
        }

        public ActionResult WriteAgingToExcel(DateTime? asofDate = null)
        {
            DateTime asOfDate = asofDate ?? DateTime.Now;

            List<Aging> a = VoucherRepository.GetAging(asOfDate);

            try
            {
                //Name of File 
                string fileName = asOfDate.ToString("dd MMM yyyy") + " Aging Report";
                string fullPath = _webHostEnvironment.WebRootPath + "/SpreadSheets/Reports/";

                System.IO.DirectoryInfo di = new DirectoryInfo(fullPath);

                using (XLWorkbook wb = new XLWorkbook())
                {
                    a = a.OrderBy(x => x.Entity).ToList();
                    string[] entity = a.Select(x => x.Entity + " - " + x.Bank).Distinct().ToArray();

                    for (int i = 0; i < entity.Length; i++)
                    {
                        var currentEntity = a.Where(x => (x.Entity + " - " + x.Bank) == entity[i]).ToList();

                        var ws = wb.Worksheets.Add(entity[i]);
                        ws.Cell("A1").Value = "SHAKEYS PIZZA ASIA VENTURES INC";
                        ws.Cell("A2").Value = "AGING OF UNRELEASED CHECKS - " + entity[i];
                        ws.Cell("A3").Value = "AS OF " + asOfDate.ToString("MMM dd, yyyy");
                        ws.Cell("A1").Style.Font.FontSize = 13;
                        ws.Cell("A2").Style.Font.FontSize = 13;
                        ws.Cell("A3").Style.Font.FontSize = 13;
                        ws.Cell("A1").Style.Font.Bold = true;
                        ws.Cell("A2").Style.Font.Bold = true;
                        ws.Cell("A3").Style.Font.Bold = true;

                        ws.Cell("K7").SetDataType(XLDataType.Text);

                        ws.Cell("A7").Value = "CHECK";
                        ws.Cell("B7").Value = "PAYEE";
                        ws.Cell("C7").Value = "DATE RECEIVED";
                        ws.Cell("D7").Value = "NO OF DAYS";
                        ws.Cell("E7").Value = "TERM";
                        ws.Cell("F7").Value = "DUE DATE";
                        ws.Cell("G7").Value = "OVER DUE";
                        ws.Cell("H7").Value = "CHECK DATE";
                        ws.Cell("I7").Value = "AMOUNT";
                        ws.Cell("J7").Value = "CURRENT";
                        ws.Cell("K7").Value = "1 to 30";
                        ws.Cell("L7").Value = "31 to 60";
                        ws.Cell("M7").Value = "61 to 90";
                        ws.Cell("N7").Value = "91 to 120";
                        ws.Cell("O7").Value = "OVER 120";
                        ws.Cell("P7").Value = "AMOUNT";
                        ws.Cell("R7").Value = "REMARKS";

                        ws.Row(7).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Center);
                        ws.Row(7).Style.Font.Bold = true;
                        ws.Row(7).Style.Font.FontSize = 12;

                        ws.Cell(9, 1).Value = currentEntity.Select(x => new {
                            x.CheckNumber,
                            x.Payee,
                            x.DateReceived,
                            noOfDays = x.NoOfDays == 0 ? "" : x.NoOfDays.ToString(),
                            x.Term,
                            dueDate = x.DueDate == null ? "" : (x.DueDate ?? DateTime.Now).ToString("MM/dd/yyyy"),
                            overDue = x.OverDue == null ? "" : x.OverDue.ToString(),
                            checkDate = x.CheckDate == null ? "" : (x.CheckDate ?? DateTime.Now).ToString("MM/dd/yyyy"),
                            x.Amount,
                            current = x.Current == null ? "" : string.Format("{0:n}", Math.Round((x.Current ?? 0), 2)),
                            term1 = x.Term1 == null ? "" : string.Format("{0:n}", Math.Round((x.Term1 ?? 0), 2)),
                            term2 = x.Term2 == null ? "" : string.Format("{0:n}", Math.Round((x.Term2 ?? 0), 2)),
                            term3 = x.Term3 == null ? "" : string.Format("{0:n}", Math.Round((x.Term3 ?? 0), 2)),
                            term4 = x.Term4 == null ? "" : string.Format("{0:n}", Math.Round((x.Term4 ?? 0), 2)),
                            term5 = x.Term5 == null ? "" : string.Format("{0:n}", Math.Round((x.Term5 ?? 0), 2)),
                            amount2 = string.Format("{0:n}", Math.Round((x.Amount2 ?? 0), 2))
                        }).AsEnumerable();

                        ws.Columns("A", "Z").AdjustToContents();
                        ws.Columns("A", "Z").Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Center);
                        ws.Column(17).Hide();
                    }

                    wb.SaveAs(fullPath + fileName + ".xlsx");

                    using (MemoryStream stream = new MemoryStream())
                    {
                        wb.SaveAs(stream);
                        //Return xlsx Excel File  

                        SystemLog sl = new SystemLog
                        {
                            logDate = DateTime.Now,
                            userId = User.Identity.Name,
                            type = "REPORT",
                            description = "Requested an aging report (excel)",
                            status = "SUCCESS"
                        };

                        SystemLogRepository.Add(sl);

                        return Json(fileName);
                    }
                }

            }
            catch (Exception)
            {
                return Json("ERROR");
            }
        }

        public void InsertTableBorder(IXLWorksheet ws, string range, string borderColor = "#4B4B4B")
        {
            ws.Range(range).Style.Border.BottomBorder =
                XLBorderStyleValues.Thin;
            ws.Range(range).Style.Border.BottomBorderColor =
                XLColor.FromHtml(borderColor);

            ws.Range(range).Style.Border.RightBorder =
                XLBorderStyleValues.Thin;
            ws.Range(range).Style.Border.RightBorderColor =
                XLColor.FromHtml(borderColor);

            ws.Range(range).Style.Border.LeftBorder =
                XLBorderStyleValues.Thin;
            ws.Range(range).Style.Border.LeftBorderColor =
                XLColor.FromHtml(borderColor);

            ws.Range(range).Style.Border.TopBorder =
                XLBorderStyleValues.Thin;
            ws.Range(range).Style.Border.TopBorderColor =
                XLColor.FromHtml(borderColor);

            ws.Range(range).Style.Border.OutsideBorder =
                XLBorderStyleValues.Thin;
            ws.Range(range).Style.Border.OutsideBorderColor =
                XLColor.FromHtml(borderColor);
        }

        public ActionResult WriteReleasedToExcel(DateTime? dateFrom, DateTime? dateTo, bool isSendToMail = false)
        {
            if (isSendToMail == true)
            {
                BackgroundJob.Enqueue(() => SendEODMail(User.Identity.Name, dateFrom, dateTo, isSendToMail));
                return Json("SUCCESS");
            }
            else
            {

                return Json(GlobalClass.WriteReleasedToExcel(User.Identity.Name, dateFrom, dateTo, isSendToMail));
            }
        }

        public void SendEODMail(string user, DateTime? dateFrom, DateTime? dateTo, bool isSendToMail = false)
        {
            GlobalClass.
            BackgroundD65Integration(DateTime.Today.AddDays(-1),
            DateTime.Today.AddDays(1));

            GlobalClass.WriteReleasedToExcel(user, dateFrom, dateTo, isSendToMail);
        }
    }
}

TDIPSNetCore/Views/Report/Aging.cshtml
<div class="clearfix"></div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="margin-top: 6px;">
            <div class="x_title">
                <div class="md-flex" style="display:flex;justify-content:space-between">
                    <div>
                        <label style="font-size: 23px;">Aging</label> <label id="txtAsOfDate" style="margin-left:4px;font-size:20px;font-weight:500;"></label>
                    </div>
                    <div class="md-flex" style="display:flex;justify-content:flex-end;">
                        <div class="input-group" style="margin-right:15px;width:50px;">
                            <span class="input-group-btn">
                                <button id="btnSet" class="btn btn-sm btn-danger"><i class="fa fa-calendar"></i> Set as of Date</button>
                            </span>
                            <input type="text" style="padding-left:19px;height:30px;width:111px;" class="form-control has-feedback-left" id="single_cal2" aria-describedby="inputSuccess2Status2">
                        </div>
                        <button type="button" id="btnExport" style="height:30px;" downloadurl="@Url.Action("DownloadExcel","Report")" url="@Url.Action("WriteAgingToExcel", "Report")" class="btn btn-sm btn-success mt-5"><i class="fa fa-external-link"></i> Export to Excel</button>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="dtPayment" class="table jambo_table bulk_action"
                       url="@Url.Action("GetPaymentsList","SEAN")?status=UNRELEASED&status=FOR VERIFIFICATION&status=FOR APPROVAL&status=FOR RELEASING&status=UNCOLLECTED&status=ON HOLD&status=REVERSED&status=REQUESTED FOR HOLD">
                    <thead>
                        <tr>
                            <th>Entity</th>
                            <th>Voucher</th>
                            <th>Check</th>
                            <th>Payee</th>
                            <th>Date Received</th>
                            <th>No of Days</th>
                            <th>Term</th>
                            <th>Due Date</th>
                            <th>Overdue</th>
                            <th>Check Date</th>
                            <th>Amount</th>
                            <th>Current</th>
                            <th>1-30</th>
                            <th>31-60</th>
                            <th>61-90</th>
                            <th>91-120</th>
                            <th>Over 120</th>
                            <th>Amount</th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<style>
    @@media only screen and (max-width: 768px) {
        .md-flex {
            flex-wrap: wrap;
            justify-content: unset !important;
        }

        #txtAsOfDate {
            margin-left: 0px !important;
        }
    }
</style>

@section styles {
    <link href="~/css/datatable.css" rel="stylesheet" />
    <link href="~/css/daterangepicker.css" rel="stylesheet" />
}


@section scripts_source {
    <script src="@Url.Content("~/js/datatable.js")"></script>
    <script src="@Url.Content("~/js/moment.min.js")"></script>
    <script src="@Url.Content("~/js/daterangepicker.js")"></script>
    <script src="@Url.Content("~/js/Page JS/aging.js")"></script>
}

TDIPSNetCore/Views/Report/CollectedCheckReport.cshtml
<div class="page-title pb-3">
    <div class="title_left">

    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <div class="md-flex" style="display:flex;justify-content:space-between;width:100%;">
                    <div style="width:100%;">
                        <h3 style="display:inline-block;font-weight:600;">Collected Checks</h3>
                        <label id="lblDate" style="margin-left:12px;font-size:16px;font-weight:600 !important;"></label>
                    </div>
                    <div class="md-flex" style="display:flex;width:100%;justify-content:flex-end;">
                        <div style="margin-top:9px;margin-right:9px;">
                            <button type="button" id="btnExport" downloadurl="@Url.Action("DownloadExcel","Report")" url="@Url.Action("WriteReleasedToExcel", "Report")" class="btn btn-success btn-sm"><i class="fa fa-external-link"></i> Export to Excel</button>
                        </div>
                        <div class="input-group" style="margin-top:9px;width:50px;">
                            <span class="input-group-btn">
                                <button id="btnSearch" class="btn btn-sm btn-danger"><i class="fa fa-search"></i> Search</button>
                            </span>
                            <input type="text" style="width: 185px" readonly="readonly" id="dtrSearch" class="form-control input-sm" value="@DateTime.Now.ToString("MM/dd/yyyy") - @DateTime.Now.ToString("MM/dd/yyyy")">
                        </div>
                    </div>
                </div>
                <div style="display:flex;align-items:center;justify-content:flex-end">
                    <label style="margin-bottom:0px;font-size:15px;margin-right:7px;">Select Check Type :</label>
                    <select id="txtCheckType" style="width:170px;height:34px;font-weight:600;border-color:#c78383;color:#333333" class="form-control">
                        <option value="STANDARD">Standard Check</option>
                        <option value="MANAGER">Manager's Check</option>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="x_panel" style="height:auto;">
                    <div class="x_title" style="padding-bottom: 0px; margin-bottom: 0px;">
                        <h2 style="font-weight: 600;padding-bottom: 14px;">Collected Checks Total Amount Summary &nbsp; &nbsp; &nbsp; <label id="lblTotal"></label></h2>

                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link" style="color:#010101"><label style="margin-right:10px;">View by bank and entity </label><i class="fa fa-chevron-down"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content" style="display: none; margin-bottom: 0px;">
                        <div class="total_summary">
                            <div class="by_entity">
                                <div class="filter-header">
                                    <label>By Entity</label>
                                </div>

                                <div class="container_item">
                                </div>
                            </div>
                            <div class="by_bank">
                                <div class="filter-header">
                                    <label>By Bank</label>
                                </div>

                                <div class="container_item">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <div>
                        <table id="dtVoucher" class="table jambo_table bulk_action" style="margin-top:16px;" adverseurl="@Url.Action("AdverseVoucher", "SEAN")" reverseurl="@Url.Action("ReverseVoucher", "SEAN")" url="@Url.Action("GetCollectedChecks","SEAN")">
                            <thead>
                                <tr>
                                    <th>Released Date</th>
                                    <th>Vendor Code</th>
                                    <th>Company Name</th>
                                    <th>Voucher ID</th>
                                    <th>Amount</th>
                                    <th>Bank</th>
                                    <th>Entity</th>
                                    <th>Check Type</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    @@media only screen and (max-width: 768px) {
        .md-flex {
            flex-wrap: wrap;
            justify-content: unset !important;
        }

        #lblDate {
            margin-left: 0px !important;
        }

        h2 {
            width: 100%;
        }

        .dataTables_length label {
            display: flex;
            align-items: center;
        }

        .dataTables_length select {
            width: 60px;
            margin: 0 6px;
        }

        .dataTables_filter label {
            display: flex;
            align-items: center;
        }

        .dataTables_filter input {
            width: 150px;
        }
    }
</style>


@section styles {
    <link href="~/css/daterangepicker.css" rel="stylesheet" />
}

@section scripts_source {
    <script src="@Url.Content("~/js/datatable.js")"></script>
    <script src="@Url.Content("~/js/Gentelella Template/validator.js")"></script>
    <script src="@Url.Content("~/js/date.format.js")"></script>
    <script src="@Url.Content("~/js/moment.min.js")"></script>
    <script src="@Url.Content("~/js/daterangepicker.js")"></script>
    <script src="@Url.Content("~/js/Page JS/collectedcheckreport.js")"></script>
}